/// scrNetworkingGameSpecificConstants()

// object types
globalvar BIG_LAKE_2_LEFT, BIG_LAKE_2_RIGHT, BIG_LAKE_3, BUILDING_1, BUILDING_2;
globalvar BUILDING_3, BUILDING_4, MINE, BULLET, PLAYER, HEALTH, AMMO, TRACKS, SAND_BIG_LAKE_2_LEFT;
globalvar SAND_BIG_LAKE_2_RIGHT, SAND_BIG_LAKE_3, FLAG_RED, FLAG_BLUE, HOME_BASE_RED, HOME_BASE_BLUE;
BIG_LAKE_2_LEFT = 0;
BIG_LAKE_2_RIGHT = 1;
BIG_LAKE_3 = 2;
BUILDING_1 = 3;
BUILDING_2 = 4;
BUILDING_3 = 5;
BUILDING_4 = 6;
MINE = 7;
BULLET = 8;
PLAYER = 9;
HEALTH = 10;
AMMO = 11;
TRACKS = 12;
SAND_BIG_LAKE_2_LEFT = 13;
SAND_BIG_LAKE_2_RIGHT = 14;
SAND_BIG_LAKE_3 = 15;
FLAG_RED = 16;
FLAG_BLUE = 17;
HOME_BASE_RED = 18;
HOME_BASE_BLUE = 19;

// sound types
globalvar SOUND_MAIN_GUN, SOUND_ITEM, SOUND_FLAG, SOUND_FANFARE, SOUND_EXPLOSION;
SOUND_MAIN_GUN = 0
SOUND_ITEM = 1
SOUND_FLAG = 2
SOUND_FANFARE = 3
SOUND_EXPLOSION = 4
